// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twdfldgnwtygbecexhma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3ZGZsZGdud3R5Z2JlY2V4aG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzEyMzEsImV4cCI6MjA3Mzk0NzIzMX0.36ZWocJQvJ16MD0GwHxn032daUuRpw51TMyIDQ25M48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});